import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import HeaderFooter from "@/components/HeaderFooter";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="font-spaceMono">
      <body className="bg-secondary-100 flex flex-col min-h-screen ">
        <NavBar />
        <main className=" flex-grow">
        {children}
        </main>
        <HeaderFooter />
        <Footer />
        </body>
    </html>
  );
}
